# Generated by Django 4.2 on 2023-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar-default.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
