# Generated by Django 4.2 on 2023-04-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_artwork_author_alter_imagefile_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.tag'),
        ),
    ]
