# Generated by Django 4.2 on 2023-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='artwork',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
