# Generated by Django 4.2 on 2023-05-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_alter_artwork_options_favoriteartwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteartwork',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favored_by', to='artworks.artwork'),
        ),
    ]
