# Generated by Django 4.2 on 2023-05-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_alter_artwork_options_artwork_source'),
        ('artworks', '0005_alter_favoriteartwork_artwork'),
    ]

    operations = [
    ]
