# Generated by Django 4.2 on 2023-05-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_merge_20230507_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteartwork',
            options={'ordering': ['-created_at']},
        ),
    ]
