# Generated by Django 4.2 on 2023-05-11 21:03

import artworks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='compressed_file',
            field=models.ImageField(blank=True, null=True, upload_to=artworks.models.uploaded_artfiles_directory_path),
        ),
    ]
