version: '3.8'

services:
  web:
    build: ../weeb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./weeb/:/usr/src/weeb/weeb/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=weeb_postgres_user
      - POSTGRES_PASSWORD=hello_postgres_123
      - POSTGRES_DB=weeb_db

volumes:
  postgres_data:
