# Generated by Django 4.2 on 2023-05-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionartwork',
            options={'ordering': ['-created_at']},
        ),
    ]
